### ISSUE TITLE
Missing Jupyter Book

### ISSUE THREAD

**Issue by AdamRJensen** [PV-Tutorials/2024_PVSC#3]
The [README](https://github.com/PV-Tutorials/2024_PVSC/blob/main/README.md) currently states

> You can also select Colaboratory from the launch icon at the top of each tutorial in the [Jupyter book](https://pvsc-tutorials.github.io/2024_PVSC/index.html).

However, there's no build action in the repository and there's no Jupyter Book, consequently, the link doesn't work: https://pvsc-tutorials.github.io/2024_PVSC/index.html

Do we want to fix this?

**Comment by madisonghiz** [comment]
I think your addition of the collab links should be good enough here, but I'm not as familiar with the build from the Jupyter Book. What do you think?

**Comment by AdamRJensen** [comment]
> I think your addition of the collab links should be good enough here, but I'm not as familiar with the build from the Jupyter Book. What do you think? 

The links are probably fine, but we need to remove the mention of the Jupyter Book then

**Comment by shirubana** [comment]
Hi, forgot to tag this thread but I added the jupyter books
